Repository LerianStudio/helm, pull requests merged in 2025-04, with the labels that each got.

#88 feat(chart): add deployment strategy in templates
  charts/midaz/templates/console/deployment.yaml
  charts/midaz/templates/onboarding/deployment.yaml
  charts/midaz/templates/transaction/deployment.yaml
  charts/midaz/values.yaml
Labels: dependencies, values, console, onboarding, transaction

#89 feat(chart): add pdb template
  charts/midaz/templates/console/pdb.yaml
  charts/midaz/templates/onboarding/pdb.yaml
  charts/midaz/templates/transaction/pdb.yaml
  charts/midaz/values.yaml
Labels: dependencies, values, console, onboarding, transaction

#92 feat(chart): update app version
  README.md
  charts/midaz/Chart.yaml
  charts/midaz/templates/onboarding/configmap.yaml
  charts/midaz/templates/transaction/configmap.yaml
  charts/midaz/values.yaml
Labels: doc, dependencies, values, onboarding, transaction

#93 feat(chart): update app version
  CHANGELOG.md
  README.md
  charts/midaz/Chart.yaml
  charts/midaz/templates/console/deployment.yaml
  charts/midaz/templates/console/pdb.yaml
  charts/midaz/templates/onboarding/configmap.yaml
  charts/midaz/templates/onboarding/deployment.yaml
  charts/midaz/templates/onboarding/pdb.yaml
  charts/midaz/templates/transaction/configmap.yaml
  charts/midaz/templates/transaction/deployment.yaml
  charts/midaz/templates/transaction/pdb.yaml
  charts/midaz/values.yaml
Labels: doc, dependencies, values, console, onboarding, transaction

#95 refactor(chart): rename helm chart
  README.md
  charts/midaz/Chart.yaml
Labels: doc, dependencies, values

#96 chore(doc): update release version
  README.md
Labels: doc

#97 chore(doc): update release version
  README.md
Labels: doc

#99 chore(chart): update helm chart parameters
  README.md
  charts/midaz/README.md
  charts/midaz/templates/console/configmap.yaml
  charts/midaz/templates/console/secrets.yaml
  charts/midaz/templates/onboarding/configmap.yaml
  charts/midaz/templates/onboarding/secrets.yml
  charts/midaz/templates/transaction/configmap.yaml
  charts/midaz/templates/transaction/secrets.yml
  charts/midaz/values.yaml
  image/README/midaz-banner.png
Labels: doc, dependencies, values, console, onboarding, transaction

#100 chore(chart): updating helm chart parameters
  CHANGELOG.md
  README.md
  charts/midaz/Chart.yaml
  charts/midaz/README.md
  charts/midaz/templates/console/configmap.yaml
  charts/midaz/templates/console/secrets.yaml
  charts/midaz/templates/onboarding/configmap.yaml
  charts/midaz/templates/onboarding/secrets.yml
  charts/midaz/templates/transaction/configmap.yaml
  charts/midaz/templates/transaction/secrets.yml
  charts/midaz/values.yaml
  image/README/midaz-banner.png
Labels: doc, dependencies, values, console, onboarding, transaction

#101 feat(chart): create plugin access manager helm chart
  .github/configs/.releaserc.json
  .github/workflows/release.yml
  .gitignore
  .releaserc.yml
  charts/plugin-access-manager/Chart.yaml
  charts/plugin-access-manager/files/00_init.sql
  charts/plugin-access-manager/files/init_data.json
  charts/plugin-access-manager/templates/NOTES.txt
  charts/plugin-access-manager/templates/auth/configmap-auth-db.yaml
  charts/plugin-access-manager/templates/auth/configmap-config.yaml
  charts/plugin-access-manager/templates/auth/configmap-init-config.yaml
  charts/plugin-access-manager/templates/auth/configmap.yaml
  charts/plugin-access-manager/templates/auth/deployment.yaml
  charts/plugin-access-manager/templates/auth/hpa.yaml
  charts/plugin-access-manager/templates/auth/pdb.yaml
  charts/plugin-access-manager/templates/auth/secrets.yaml
  charts/plugin-access-manager/templates/auth/service.yaml
  charts/plugin-access-manager/templates/helpers.tpl
  charts/plugin-access-manager/templates/identity/configmap.yaml
  charts/plugin-access-manager/templates/identity/deployment.yaml
  charts/plugin-access-manager/templates/identity/hpa.yaml
  charts/plugin-access-manager/templates/identity/pdb.yaml
  charts/plugin-access-manager/templates/identity/secrets.yaml
  charts/plugin-access-manager/templates/identity/service.yaml
  charts/plugin-access-manager/values.yaml
Labels: pipe

#104 feat(doc): update charts docs
  README.md
  charts/midaz/README.md
  charts/plugin-access-manager/README.md
Labels: doc, dependencies, values

#105 feat(doc): add plugin access manager documentation
  CHANGELOG.md
  README.md
  charts/midaz/Chart.yaml
  charts/midaz/README.md
  charts/plugin-access-manager/Chart.yaml
  charts/plugin-access-manager/README.md
Labels: doc, dependencies, values

#108 feat(chart): add pdb to auth backend
  charts/plugin-access-manager/templates/auth-backend/pdb.yaml
Labels: chart

#110 refactor(chart): auth backend rename default app
  charts/plugin-access-manager/files/init_data.json
Labels: dependencies, chart

#113 feat(console): update app version
  CHANGELOG.md
  charts/midaz/Chart.yaml
  charts/midaz/templates/console/configmap.yaml
  charts/midaz/values.yaml
  charts/plugin-access-manager/Chart.yaml
Labels: dependencies, values, console

#114 docs(chart): update midaz chart readme
  README.md
  charts/midaz/README.md
Labels: doc, dependencies, values

#119 docs(chart): fix helm release name
  CHANGELOG.md
  README.md
  charts/plugin-access-manager/Chart.yaml
  charts/plugin-access-manager/README.md
Labels: doc

#122 feat(console): update version
  charts/midaz/Chart.yaml
  charts/midaz/templates/console/configmap.yaml
  charts/midaz/values.yaml
Labels: dependencies, values, console

#123 feat(console): update version
  CHANGELOG.md
  charts/midaz/Chart.yaml
  charts/midaz/templates/console/configmap.yaml
  charts/midaz/values.yaml
Labels: dependencies, values, console

#124 docs(doc): update versions matrix
  README.md
  charts/midaz/README.md
Labels: doc, dependencies, values

#125 docs(doc): update versions matrix
  CHANGELOG.md
  README.md
  charts/midaz/Chart.yaml
  charts/midaz/README.md
  charts/plugin-access-manager/Chart.yaml
Labels: doc, dependencies, values

#126 fix(pipe): set changelog
  .github/workflows/release.yml
  CHANGELOG.md
  charts/midaz/Chart.yaml
  charts/plugin-access-manager/Chart.yaml
Labels: pipe, dependencies, values

#127 feat(chart): add plugin crm helm templates
  .github/configs/.releaserc.json
  .github/workflows/release.yml
  charts/plugin-crm/Chart.yaml
  charts/plugin-crm/README.md
  charts/plugin-crm/templates/NOTES.txt
  charts/plugin-crm/templates/configmap.yaml
  charts/plugin-crm/templates/deployment.yaml
  charts/plugin-crm/templates/helpers.tpl
  charts/plugin-crm/templates/hpa.yaml
  charts/plugin-crm/templates/ingress.yaml
  charts/plugin-crm/templates/pdb.yaml
  charts/plugin-crm/templates/secrets.yaml
  charts/plugin-crm/templates/service.yaml
  charts/plugin-crm/values.yaml
Labels: pipe
